### PR TITLE
Transfer ESP32 support from Azure IoT to Espressif

### PR DESCRIPTION
**Pull request by JetstreamRoySprowl**
This pull request supersedes the one made earlier against the [Espressif SDK](https://github.com/espressif/esp-idf), which will be removed. 

This pull request addresses the changes requested for the earlier pull request.

### CODE REVIEW

**Comment by ustccw** [comment]
@JetstreamRoySprowl very thanks for your pull requests, would you mind providing a azure connection string for us to test this PR?

**Comment by JetstreamRoySprowl** [comment]
@ustccw I just sent a connection string via email.

**Comment by ustccw** [comment]
@JetstreamRoySprowl thanks a lot. i received your email and would test it.

**Comment by ustccw** [comment]
@JetstreamRoySprowl thanks for your work. this PR had merged master branch.

**Pull request merged**
